### ISSUE TITLE
Actual content doesn't get removed from DOM when egg activates

### ISSUE THREAD

**Issue by magician11** [scriptwerx/angular-egg#1]
Hi there,

Cool module. The content of `<section data-ng-if="!vm.eggActivated">` doesn't get removed from the DOM though when the egg is activated.

I think that's because `vm.eggActivated` is accessible within the scope of `<section data-ng-egg>` only.

Demo here: http://plnkr.co/edit/33Tk43CgbHXEPdUemPHQ

**Comment by theDustRoom** [comment]
Hi Andrew;

Thanks; when I read about '[egg.js](http://thatmikeflynn.com/egg.js/)' I just had to use it in our AngularJS apps!

As our code is designed with using the "controller as" way of writing AngularJS apps;
'vm.eggActivated' wouldn't work because 'vm' is undefined.

Todd Motto did a good writeup on this feature:
http://toddmotto.com/digging-into-angulars-controller-as-syntax/

It's easily missed; I'll maybe update the README with better information.

Anyway; heres's a working demo: http://plnkr.co/edit/w4jiGgsYfhW8QLXk3HSF?p=preview

**Comment by magician11** [comment]
Hi Paul,

Thanks for clarifying. Funnily enough I was actually using that egg.js script you mentioned in an AngularJS app of mine. So I started to re-write an AngularJS version so I could drop the dependency on jQuery. And that's when I came across yours :+1: 

Thanks for updating my demo too. Helps a lot.
