### ISSUE TITLE
angular-egg actually changes element's CSS

### ISSUE THREAD

**Issue by mboudreau** [scriptwerx/angular-egg#4]
This is against Angular convention, is bad practice and it overrides any changes that are done within a css file.

By default, it should _only_ modify a model so that others directives and the like can decide what to do.

**Comment by theDustRoom** [comment]
The idea is to have a simple show/hide which is why it's configured as so to make it very simple to use.

It's very little code which can easily be decorated or absorbed into an existing codebase and is designed primarily as a demonstration.

Having said that; there is an update coming that does remove the CSS changes and uses model alone.

**Comment by theDustRoom** [comment]
Sorry for the epic delay with updating this; it's now been resolved.
